# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Png8vm5H6SMMbO1P29CaZPr3EawcUj10
"""

import numpy as np
from abc import ABC, abstractmethod
from Allocator.base import Allocator


class CPPIAllocator(Allocator):
    """
    CPPI overlay au-dessus d'un allocateur risqué (ex: MeanVarianceAllocator)
    """

    def __init__(self,
                 allocator_risky: Allocator,
                 multipliers: np.ndarray,
                 floor_pct: float = 0.8,
                 initial_value: float = 1.0):

        self.allocator_risky = allocator_risky
        self.multipliers = np.array(multipliers)
        self.floor_pct = floor_pct
        self.initial_value = initial_value

        self.V_t = initial_value
        self.floor_value = floor_pct * initial_value
        self._current_probs = None

    def set_mu(self, mu: np.ndarray):
        self.allocator_risky.set_mu(mu)

    def set_regime_probs(self, predictive_probs: np.ndarray):
        self._current_probs = predictive_probs

    def allocate(self, Sigma: np.ndarray) -> np.ndarray:

        if self._current_probs is None:
            raise ValueError("Probabilités de régime non définies.")

        # 1️⃣ Multiplicateur dépendant du régime
        m_t = np.dot(self._current_probs, self.multipliers)

        # 2️⃣ Cushion
        cushion = max(self.V_t - self.floor_value, 0)

        # 3️⃣ Exposition totale risquée
        risky_exposure = min(m_t * cushion, self.V_t)
        risky_weight_total = risky_exposure / self.V_t if self.V_t > 0 else 0

        # 4️⃣ Allocation interne (Mean-Variance)
        w_risky = self.allocator_risky.allocate(Sigma)

        w_risky = w_risky / (np.sum(np.abs(w_risky)) + 1e-12)

        return risky_weight_total * w_risky

    def update_portfolio_value(self, realized_return: float):
        self.V_t *= (1 + realized_return)